apiVersion: v1
kind: Service
metadata:
  name: jupyter-spark-notebook
  labels:
    app: jupyter-spark-notebook
    spark-version: 3.3.0-scala_2.12-jre_17
spec:
  type: LoadBalancer
  selector:
    app: jupyter-spark-notebook
    spark-version: 3.3.0-scala_2.12-jre_17
  ports:
  - name: http
    port: 8888
    protocol: TCP
  - name: sparkui
    port: 4040
    protocol: TCP
  - name: blockmanager
    port: 7777
    protocol: TCP
  - name: driver
    port: 2222
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-headless
  labels:
    app: jupyter-spark-notebook
    spark-version: 3.3.0-scala_2.12-jre_17
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: false
  selector:
    app: jupyter-spark-notebook
    spark-version: 3.3.0-scala_2.12-jre_17
  ports:
  - name: http
    port: 8888
    protocol: TCP
  - name: sparkui
    port: 4040
    protocol: TCP
  - name: blockmanager
    port: 7777
    protocol: TCP
  - name: driver
    port: 2222
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jupyter-spark-notebook
  labels:
    app: jupyter-spark-notebook
    spark-version: 3.3.0-scala_2.12-jre_17
    #cuda-image: 11.7.1-cudnn8-runtime-ubuntu22.04
spec:
  replicas:
  updateStrategy:
    type: RollingUpdate
  serviceName: jupyter-headless
  podManagementPolicy: Parallel
  volumeClaimTemplates:
  - metadata:
      name: notebook-data
      labels:
        app: jupyter-spark-notebook
        spark-version: 3.3.0-scala_2.12-jre_17
        #cuda-image: 11.7.1-cudnn8-runtime-ubuntu22.04
    spec:
      accessModes:
      - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 2Gi
      storageClassName: microk8s-hostpath
  selector:
    matchLabels:
      app: jupyter-spark-notebook
      spark-version: 3.3.0-scala_2.12-jre_17
      #cuda-image: 11.7.1-cudnn8-runtime-ubuntu22.04
  template:
    metadata:
      labels:
        app: jupyter-spark-notebook
        spark-version: 3.3.0-scala_2.12-jre_17
        #cuda-image: 11.7.1-cudnn8-runtime-ubuntu22.04
      annotations:
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: datastoryteller-ml-data-deployer
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: jupyter-spark-notebook
        image: "datastoryteller/spark-notebook:3.3.0-scala_2.12-jre_17-slim-bullseye"
        #image: "datastoryteller/gpu-jupyter-spark:v1.4_cuda-11.7_ubuntu-22.04_slim"
        imagePullPolicy: Always
        env:
          - name: S3_HOST_URL
            valueFrom:
              secretKeyRef:
                name: minio-api-client-credentials
                key: MINIO_HOST_URL
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-api-client-credentials
                key: MINIO_ACCESS_KEY
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-api-client-credentials
                key: MINIO_SECRET_KEY
        ports:
        - name: http
          containerPort: 8888
          protocol: TCP
        - name: sparkui
          containerPort: 4040
          protocol: TCP
        - name: blockmanager
          containerPort: 7777
          protocol: TCP
        - name: driver
          containerPort: 2222
          protocol: TCP
        volumeMounts:
        - name: notebook-data
          mountPath: /home/notebook
        resources:
          limits:
            cpu: 2000m
            memory: 4096Mi
          requests:
            cpu: 2000m
            memory: 4096Mi