apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-deploy-binding
  namespace: ml-data-engg
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-deploy # name of Role
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: ds-deployer # service account to bind to
  namespace: ml-data-engg # ns of service account